[package]
name = "nostrhole"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
async-compression = { version = "0.4.18", features = ["tokio", "zstd"] }
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
config = { version = "0.14.1", features = ["yaml"] }
log = "0.4.22"
nostr-relay-builder = { git = "https://github.com/rust-nostr/nostr.git", rev = "f21ffbd2de4e9ad87cd8345158039754cee05031", package = "nostr-relay-builder" }
pretty_env_logger = "0.5.0"
sled = "0.34.7"
tokio = { version = "1.42.0", features = ["macros", "fs", "rt", "rt-multi-thread", "signal"] }
warp = "0.3.7"
serde = { version = "1.0.216", features = ["derive"] }
nostr-sdk = { git = "https://github.com/rust-nostr/nostr.git", rev = "f21ffbd2de4e9ad87cd8345158039754cee05031", package = "nostr-sdk" }
